# Generated by Django 6.0.3 on 2026-05-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0004_booking_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(help_text='Category cover image', upload_to='dome_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dome Categories',
            },
        ),
        migrations.CreateModel(
            name='DomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='domes/')),
                ('check_in', models.CharField(default='12:00 PM', max_length=20)),
                ('check_out', models.CharField(default='11:00 AM', max_length=20)),
                ('normal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_items', models.TextField(help_text='Enter items separated by new lines')),
                ('facilities', models.TextField(help_text='Enter facilities separated by new lines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domes', to='domesinnheaven_app.domecategory')),
            ],
            options={
                'verbose_name': 'Dome Type',
                'verbose_name_plural': 'Dome Types',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='dome_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domesinnheaven_app.dometype'),
        ),
    ]
