# Generated by Django 6.0.3 on 2026-05-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0005_domecategory_dometype_booking_dome_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='domecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description'),
        ),
    ]
