# Generated by Django 6.0.3 on 2026-05-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0006_domecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dome_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domesinnheaven_app.domecategory'),
        ),
    ]
