# Generated by Django 6.0.3 on 2026-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0007_booking_dome_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domecategory',
            name='description',
        ),
    ]
