# Generated by Django 6.0.3 on 2026-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0010_alter_activity_slug_alter_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dometype',
            name='facilities',
            field=models.TextField(blank=True, default='', help_text='Enter facilities separated by new lines'),
        ),
        migrations.AlterField(
            model_name='dometype',
            name='package_items',
            field=models.TextField(blank=True, default='', help_text='Enter items separated by new lines'),
        ),
    ]
