# Generated by Django 6.0.3 on 2026-09-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0011_alter_dometype_facilities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dometype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dome Type', 'verbose_name_plural': 'Dome Types'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dome_category',
        ),
        migrations.RemoveField(
            model_name='dometype',
            name='category',
        ),
        migrations.AlterField(
            model_name='dometype',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
