# Generated by Django 6.0.3 on 2026-09-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0012_alter_dometype_options_remove_booking_dome_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='jacuzzi_bathtub',
            field=models.BooleanField(default=False, help_text='Guest requested Jacuzzi bathtub'),
        ),
    ]
