# Generated by Django 6.0.3 on 2026-09-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0013_booking_jacuzzi_bathtub'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomeTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='domes/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dome_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='domesinnheaven_app.dometype')),
            ],
            options={
                'verbose_name': 'Dome Type Image',
                'verbose_name_plural': 'Dome Type Images',
                'ordering': ['id'],
            },
        ),
    ]
