# Generated by Django 6.0.3 on 2026-09-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0014_dometypeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dometype',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='domes/gallery/'),
        ),
        migrations.AlterField(
            model_name='dometypeimage',
            name='dome_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='domesinnheaven_app.dometype'),
        ),
    ]
