# Generated by Django 6.0.3 on 2026-10-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0015_alter_dometype_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='jacuzzi_bathtub',
        ),
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.JSONField(blank=True, default=list, help_text='Selected booking add-ons'),
        ),
    ]
