# Generated by Django 6.0.3 on 2026-10-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0016_remove_booking_jacuzzi_bathtub_booking_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomeFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dome_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='domesinnheaven_app.dometype')),
            ],
            options={
                'verbose_name': 'Dome FAQ',
                'verbose_name_plural': 'Dome FAQs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
