# Generated by Django 6.0.3 on 2026-10-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0017_domefaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='addons',
        ),
    ]
